CREATE TABLE IF NOT EXISTS duels (
 id CHAR(32) PRIMARY KEY, seed INT UNSIGNED NOT NULL,
 starts_at_ms BIGINT UNSIGNED NOT NULL, ends_at_ms BIGINT UNSIGNED NOT NULL,
 status ENUM('active','finished') NOT NULL DEFAULT 'active',
 winner_id BIGINT UNSIGNED NULL, reason VARCHAR(30) NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(status,ends_at_ms)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS duel_players (
 duel_id CHAR(32) NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 seat TINYINT UNSIGNED NOT NULL, nonce CHAR(32) NOT NULL,
 score INT UNSIGNED NOT NULL DEFAULT 0, lives TINYINT UNSIGNED NOT NULL DEFAULT 3,
 shots INT UNSIGNED NOT NULL DEFAULT 0, hits INT UNSIGNED NOT NULL DEFAULT 0,
 misses INT UNSIGNED NOT NULL DEFAULT 0, fever_hits INT UNSIGNED NOT NULL DEFAULT 0,
 max_streak INT UNSIGNED NOT NULL DEFAULT 0, last_shot_ms INT NOT NULL DEFAULT -350,
 last_seen_ms BIGINT UNSIGNED NOT NULL, finished TINYINT(1) NOT NULL DEFAULT 0,
 forfeited TINYINT(1) NOT NULL DEFAULT 0,
 PRIMARY KEY(duel_id,user_id), UNIQUE KEY(duel_id,seat), INDEX(user_id,finished),
 FOREIGN KEY(duel_id) REFERENCES duels(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS duel_events (
 duel_id CHAR(32) NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 seq INT UNSIGNED NOT NULL, payload MEDIUMTEXT NOT NULL, payload_hash CHAR(64) NOT NULL,
 PRIMARY KEY(duel_id,user_id,seq),
 FOREIGN KEY(duel_id,user_id) REFERENCES duel_players(duel_id,user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS duel_queue (
 user_id BIGINT UNSIGNED PRIMARY KEY, joined_ms BIGINT UNSIGNED NOT NULL,
 last_seen_ms BIGINT UNSIGNED NOT NULL, INDEX(last_seen_ms,joined_ms),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth_challenges (
 id CHAR(32) PRIMARY KEY, nonce_hash CHAR(64) NOT NULL,
 expires_at DATETIME NOT NULL, used_at DATETIME NULL, INDEX(expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
