CREATE TABLE users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, public_id CHAR(26) NOT NULL UNIQUE,
 email VARCHAR(190) NULL UNIQUE, password_hash VARCHAR(255) NULL,
 username VARCHAR(20) NULL, username_key VARCHAR(20) NULL UNIQUE,
 display_name VARCHAR(80) NULL, avatar_url VARCHAR(500) NULL,
 status ENUM('active','suspended','deleted') NOT NULL DEFAULT 'active',
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 last_seen_at DATETIME NULL, INDEX(created_at), INDEX(last_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE identities (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL,
 provider ENUM('email','google','apple') NOT NULL, provider_subject VARCHAR(255) NOT NULL,
 email VARCHAR(190) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY(provider,provider_subject), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE refresh_tokens (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL,
 token_hash CHAR(64) NOT NULL UNIQUE, device_name VARCHAR(120) NULL,
 expires_at DATETIME NOT NULL, revoked_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE game_sessions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, public_id CHAR(32) NOT NULL UNIQUE,
 user_id BIGINT UNSIGNED NOT NULL, nonce CHAR(32) NOT NULL, score INT UNSIGNED NOT NULL DEFAULT 0,
 shots SMALLINT UNSIGNED NOT NULL DEFAULT 0, hits SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 misses SMALLINT UNSIGNED NOT NULL DEFAULT 0, fever_hits SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 max_streak SMALLINT UNSIGNED NOT NULL DEFAULT 0, duration_ms INT UNSIGNED NOT NULL DEFAULT 0,
 stage VARCHAR(20) NOT NULL DEFAULT 'street', client_version VARCHAR(24) NULL, platform VARCHAR(20) NULL,
 suspicious TINYINT(1) NOT NULL DEFAULT 0, reject_reason VARCHAR(255) NULL,
 started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, finished_at DATETIME NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX(score), INDEX(finished_at), INDEX(user_id,finished_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE daily_user_stats (
 stat_date DATE NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 sessions INT UNSIGNED NOT NULL DEFAULT 0, shots INT UNSIGNED NOT NULL DEFAULT 0,
 hits INT UNSIGNED NOT NULL DEFAULT 0, play_ms BIGINT UNSIGNED NOT NULL DEFAULT 0,
 best_score INT UNSIGNED NOT NULL DEFAULT 0, PRIMARY KEY(stat_date,user_id),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE api_rate_limits (
 bucket CHAR(64) NOT NULL, window_start DATETIME NOT NULL, hits SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 PRIMARY KEY(bucket,window_start), INDEX(window_start)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
